# Developer's Note: This is a sample _config.yml file offered with
# jekyll-theme-prologue for your convenience. To use it, move it to your
# project's root directory. Please note that the following lines are
# NECESSARY for Prologue to work correctly:
#
# theme: jekyll-theme-prologue
# collections: [sections]
#
# They activate the theme and tell Jekyll to find your homepage content
# in /_sections. Note where "sections" starts with an underscore
# and where it doesn't. The social settings will make links to
# Twitter, etc., but only if you give the URL.
#
# Also, be sure to customize url and baseurl for your site.
#
# ---------------------------------------------------------------
#

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: lapolicianomecuida
subtitle: .org
description: >- # this means to ignore newlines until "baseurl:"
  En memoria de las mujeres víctimas de represión y tortura sexual por parte de policías municipales.
author: LaPoliciaNoMeCuida.org
email: lapolicianomecuida.org@gmail.com
avatar: assets/images/avatar.jpg

baseurl: ""
# url: "" # the base hostname & protocol for your site

# Social settings
# Make sure to include the full url including protocol
twitter_url:
facebook_url:
googleplus_url:
instagram_url:
linkedin_url:
github_url:
stackoverflow_url:
pinterest_url:
slack_url:
dribbble_url:

# Google Analytics Tracking ID goes here:
google_analytics:

# The following settings are NECESSARY for the Prologue theme to run:
theme: jekyll-theme-prologue
collections: [sections]
images: 9
